SELECT
    r.PN_CHINESENAME AS empName,
    r.PN_EMPNO AS empNo,
	r.PN_EMAIL1 AS empEmail,
	r.DP_MANAGEEMPNO AS supervisorNo,
	p2.PN_EMAIL1 AS supervisorEmail
FROM
	PERSONNEL p2
INNER JOIN (
	SELECT
		p1.PN_CHINESENAME, p1.PN_EMPNO, p1.DP_CODE, p1.PN_EMAIL1, p1.PN_EMAIL2, cd.DP_MANAGEEMPNO
	FROM
		PERSONNEL p1
	LEFT JOIN CATEGORY_DEPARTMENT cd ON
		p1.DP_CODE = cd.DP_CODE
	WHERE
		p1.PN_EMPNO = :empNo ) r ON
	p2.PN_EMPNO = r.DP_MANAGEEMPNO
